name: CI_semantic_release

on:
  push:
    branches: 
      - semantic_release
    paths-ignore:
      - "**/package.json"
      - "**/*.md"
      - "**/.gitignore"

jobs:
  # install:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       shell: bash
  #       working-directory: hello-yocto
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - name: Setup Node.js
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: 12.14
  #   - name: Install
  #     run: yarn install
  #   - name: Test
  #     run: npm test

  release:
    # Only release on push to master
    # if: github.event_name == 'push' && github.ref == 'refs/heads/semantic_release'
    runs-on: ubuntu-latest
    # needs: [install]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: semantic_release
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.14
    - name: Install
      run: yarn install
    - name: Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: see directory
      run: ls
